Repository meetfranz/franz, pull requests merged in 2019-06, with the labels that each got.

#1444 logout user when access token is invalid
  src/stores/GlobalErrorStore.js
  src/stores/UserStore.js
Labels: bug

#1467 Fix close window shortcut
  package-lock.json
  src/assets/images/tray/win32/tray-unread.ico
  src/assets/images/tray/win32/tray-unread@2x.ico
  src/assets/images/tray/win32/tray.ico
  src/assets/images/tray/win32/tray@2x.ico
  src/lib/Menu.js
Labels: bug, os/windows

#1471 Use same email validation as on the api
  package-lock.json
  package.json
  src/helpers/validation-helpers.js
  src/i18n/locales/defaultMessages.json
  src/i18n/messages/src/helpers/validation-helpers.json
Labels: bug

#1469 Add check for updates menu item
  src/components/AppUpdateInfoBar.js
  src/components/auth/AuthLayout.js
  src/components/layout/AppLayout.js
  src/containers/auth/AuthLayoutContainer.js
  src/dev-app-update.yml
  src/i18n/locales/defaultMessages.json
  src/i18n/locales/en-US.json
  src/i18n/messages/src/components/AppUpdateInfoBar.json
  src/i18n/messages/src/components/layout/AppLayout.json
  src/i18n/messages/src/lib/Menu.json
  src/lib/Menu.js
Labels: enhancement

#1468 Fix invalid services references in workspaces locally
  src/features/workspaces/store.js
Labels: bug

#1473 Fix/reset news on logout
  package-lock.json
  src/stores/NewsStore.js
Labels: bug
